// <auto-generated />
using ConsultaMaisAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultaMaisAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ConsultaMaisAPI.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Consultas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MedicoId = 1,
                            PacienteId = 1
                        },
                        new
                        {
                            Id = 2,
                            MedicoId = 2,
                            PacienteId = 2
                        },
                        new
                        {
                            Id = 3,
                            MedicoId = 3,
                            PacienteId = 3
                        });
                });

            modelBuilder.Entity("ConsultaMaisAPI.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especialidade = "Cardiologista",
                            Nome = "Dr. Roberto Santos"
                        },
                        new
                        {
                            Id = 2,
                            Especialidade = "Dermatologista",
                            Nome = "Dra. Ana Souza"
                        },
                        new
                        {
                            Id = 3,
                            Especialidade = "Neurologista",
                            Nome = "Dr. Luiz Lima"
                        });
                });

            modelBuilder.Entity("ConsultaMaisAPI.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Documento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Documento = 12345678901L,
                            Nome = "João Silva"
                        },
                        new
                        {
                            Id = 2,
                            Documento = 98765432100L,
                            Nome = "Maria Oliveira"
                        },
                        new
                        {
                            Id = 3,
                            Documento = 11223344556L,
                            Nome = "Carlos Pereira"
                        });
                });

            modelBuilder.Entity("ConsultaMaisAPI.Models.Consulta", b =>
                {
                    b.HasOne("ConsultaMaisAPI.Models.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultaMaisAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
